version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_USER: ${POSTGRES_USER:-myapp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - myapp_network

  redis:
    image: redis:7-alpine
    container_name: myapp_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - myapp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    container_name: myapp_backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-myapp_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-myapp}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - myapp_network

frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
    no_cache: true
    args:
      - BUILDKIT_INLINE_CACHE=0
      - NEXT_PUBLIC_API_URL=https://n8n-karpix-communa.g44y6r.easypanel.host
      - NEXT_PUBLIC_APP_NAME=Kommuna
      - BUILD_DATE=2024-08-16-v2
  container_name: myapp_frontend_v2
  environment:
    - NEXT_PUBLIC_API_URL=https://n8n-karpix-communa.g44y6r.easypanel.host
    - NEXT_PUBLIC_APP_NAME=Kommuna
  depends_on:
    - backend
  ports:
    - "3001:3000"
  restart: unless-stopped
  networks:
    - myapp_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      no_cache: true
    container_name: myapp_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://backend:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-myapp_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-myapp}
      - WEBHOOK_URL=${WEBHOOK_URL}
    depends_on:
      - postgres
      - backend
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - myapp_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  myapp_network:
    driver: bridge
