# docker-compose.yml для Easypanel
# ИСПРАВЛЕННАЯ версия БЕЗ локального PostgreSQL

services:
  # Backend API сервер
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: communa_backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - RELOAD=false
      # ИСПОЛЬЗУЕМ ВНЕШНЮЮ БД EASYPANEL
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - TELEGRAM_WEBHOOK_DOMAIN=${TELEGRAM_WEBHOOK_DOMAIN}
      - TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}
      - TELEGRAM_MAIN_BOT_TOKEN=${TELEGRAM_MAIN_BOT_TOKEN}
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=52428800
    depends_on:
      redis:
        condition: service_started
      # УБИРАЕМ ЗАВИСИМОСТЬ ОТ POSTGRES
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    networks:
      - communa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js приложение
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: communa_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_APP_ENV=production
    depends_on:
      - backend
    networks:
      - communa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Telegram Bot
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: communa_bot
    environment:
      - TELEGRAM_MAIN_BOT_TOKEN=${TELEGRAM_MAIN_BOT_TOKEN}
      - BACKEND_URL=http://backend:8000
      - WEBAPP_URL=${TELEGRAM_WEBHOOK_DOMAIN}
      - LOG_LEVEL=INFO
      - DEBUG_MODE=false
    depends_on:
      backend:
        condition: service_started
    volumes:
      - bot_logs:/app/logs
    networks:
      - communa_network
    restart: unless-stopped
    command: ["python", "-m", "src.main"]

  # Redis для кэширования (ЕДИНСТВЕННАЯ БД В КОНТЕЙНЕРЕ)
  redis:
    image: redis:7-alpine
    container_name: communa_redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # ИЗМЕНИЛИ ВНЕШНИЙ ПОРТ
    networks:
      - communa_network
    command: redis-server --appendonly yes --maxmemory 256mb
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

# УБИРАЕМ PostgreSQL ПОЛНОСТЬЮ - используем внешнюю БД EasyPanel

volumes:
  # УБИРАЕМ postgres_data - не нужен
  redis_data:
    driver: local
  backend_logs:
    driver: local
  backend_uploads:
    driver: local
  bot_logs:
    driver: local

networks:
  communa_network:
    driver: bridge
