# docker-compose.override.yml
# Переопределения для работы с ВНЕШНЕЙ PostgreSQL БД

services:
  # ПОЛНОСТЬЮ УДАЛЯЕМ локальный PostgreSQL сервис
  postgres:
    image: alpine:latest  # Заглушка
    command: ["echo", "PostgreSQL отключен - используем внешнюю БД"]
    deploy:
      replicas: 0  # Отключаем совсем
    ports: []  # Убираем конфликтующий порт 5432
    
  # Backend - подключаем к внешней БД
  backend:
    environment:
      # Подключение к ВНЕШНЕЙ PostgreSQL БД
      - DB_HOST=162.244.24.212
      - DB_PORT=5432
      - DB_NAME=kommuna
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      # Убираем зависимость от локального postgres
      redis:
        condition: service_started
    
  # Redis - оставляем, но меняем внешний порт
  redis:
    ports:
      - "6380:6379"  # Избегаем конфликтов портов
      
  # Frontend - убираем зависимость от postgres
  frontend:
    depends_on:
      - backend
      
  # Bot - убираем зависимость от postgres
  bot:
    depends_on:
      backend:
        condition: service_started

# Убираем ненужные volumes для postgres
volumes:
  postgres_data:
    external: false  # Не используем локальный volume
